// Generated by https://quicktype.io

export class Lunchofdaytmp {
  paiva: string;
  nimi: string;
  string_agg: string;
  restaurantid: number;
  randommultiplier: string;
  restaurantmultiplier: string;
  genremultiplier: string;
  usermultiplier: string;
  totalscore: string;
}
